# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ gyosi: 'Chicago' }, { gyosi: 'Copenhagen' }])
#   Mayor.create(gyosi: 'Emanuel', city: cities.first)

Gyosiyakdok.create(gyosi: "월요일 1교시")
Gyosiyakdok.create(gyosi: "화요일 1교시")
Gyosiyakdok.create(gyosi: "수요일 1교시")
Gyosiyakdok.create(gyosi: "목요일 1교시")
Gyosiyakdok.create(gyosi: "금요일 1교시")
Gyosiyakdok.create(gyosi: "토요일 1교시")
Gyosiyakdok.create(gyosi: "일요일 1교시")
Gyosiyakdok.create(gyosi: "월요일 2교시")
Gyosiyakdok.create(gyosi: "화요일 2교시")
Gyosiyakdok.create(gyosi: "수요일 2교시")
Gyosiyakdok.create(gyosi: "목요일 2교시")
Gyosiyakdok.create(gyosi: "금요일 2교시")
Gyosiyakdok.create(gyosi: "토요일 2교시")
Gyosiyakdok.create(gyosi: "일요일 2교시")
Gyosiyakdok.create(gyosi: "월요일 3교시")
Gyosiyakdok.create(gyosi: "화요일 3교시")
Gyosiyakdok.create(gyosi: "수요일 3교시")
Gyosiyakdok.create(gyosi: "목요일 3교시")
Gyosiyakdok.create(gyosi: "금요일 3교시")
Gyosiyakdok.create(gyosi: "토요일 3교시")
Gyosiyakdok.create(gyosi: "일요일 3교시")
Gyosiyakdok.create(gyosi: "월요일 4교시")
Gyosiyakdok.create(gyosi: "화요일 4교시")
Gyosiyakdok.create(gyosi: "수요일 4교시")
Gyosiyakdok.create(gyosi: "목요일 4교시")
Gyosiyakdok.create(gyosi: "금요일 4교시")
Gyosiyakdok.create(gyosi: "토요일 4교시")
Gyosiyakdok.create(gyosi: "일요일 4교시")
Gyosiyakdok.create(gyosi: "월요일 5교시")
Gyosiyakdok.create(gyosi: "화요일 5교시")
Gyosiyakdok.create(gyosi: "수요일 5교시")
Gyosiyakdok.create(gyosi: "목요일 5교시")
Gyosiyakdok.create(gyosi: "금요일 5교시")
Gyosiyakdok.create(gyosi: "토요일 5교시")
Gyosiyakdok.create(gyosi: "일요일 5교시")
Gyosiyakdok.create(gyosi: "월요일 6교시")
Gyosiyakdok.create(gyosi: "화요일 6교시")
Gyosiyakdok.create(gyosi: "수요일 6교시")
Gyosiyakdok.create(gyosi: "목요일 6교시")
Gyosiyakdok.create(gyosi: "금요일 6교시")
Gyosiyakdok.create(gyosi: "토요일 6교시")
Gyosiyakdok.create(gyosi: "일요일 6교시")
Gyosiyakdok.create(gyosi: "월요일 7교시")
Gyosiyakdok.create(gyosi: "화요일 7교시")
Gyosiyakdok.create(gyosi: "수요일 7교시")
Gyosiyakdok.create(gyosi: "목요일 7교시")
Gyosiyakdok.create(gyosi: "금요일 7교시")
Gyosiyakdok.create(gyosi: "토요일 7교시")
Gyosiyakdok.create(gyosi: "일요일 7교시")
Gyosiyakdok.create(gyosi: "월요일 8교시")
Gyosiyakdok.create(gyosi: "화요일 8교시")
Gyosiyakdok.create(gyosi: "수요일 8교시")
Gyosiyakdok.create(gyosi: "목요일 8교시")
Gyosiyakdok.create(gyosi: "금요일 8교시")
